version: '3.1'

services:


  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Abc123


  mongo-express:
    image: mongo-express
    container_name: mexpress
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Abc123
      ME_CONFIG_MONGODB_URL: mongodb://root:Abc123@mongo:27017/
    links:
      - mongo

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      MONGO_URL: mongodb://root:Abc123@mongo:27017/development?authSource=admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Abc123
      MONGO_USERNAME: root
      MONGO_PASSWORD: Abc123
    depends_on:
      - mongo
      - mongo-express